### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by hasanelfalakiy** [skjolber/sesseltjonna-csv#144]
Does it support int and double data type? 
like

i, a, b, c
1, 0.385, 9.0252, 1.3533
2, -26.6262, 21.262, -25.362

**Comment by skjolber** [comment]
Yes. Se for example [this](https://github.com/skjolber/sesseltjonna-csv/blob/master/databinder/src/test/java/com/github/skjolber/stcsv/databinder/CsvMapperTest.java#L30) unit test.

**Comment by hasanelfalakiy** [comment]
> Yes. Se for example [this](https://github.com/skjolber/sesseltjonna-csv/blob/master/databinder/src/test/java/com/github/skjolber/stcsv/databinder/CsvMapperTest.java#L30) unit test.
> 
> 

ok, but I don't understand Java language well, because I use Kotlin, does it support skip header? and accessing columns with index?

**Comment by skjolber** [comment]
It uses the header to map the columns and then reads data from the next line. So yes, but it assumes there is an header.

This way the order of the columns can vary; as long as the header column name is the same everything will still work.

**Comment by skjolber** [comment]
So no access by index -> access by column label instead.

**Comment by hasanelfalakiy** [comment]
> So no access by index -> access by column label instead.

ok i see, I'll try it, thanks
