### ISSUE TITLE
Skip and log rows with errors

### ISSUE THREAD

**Issue by paulux84** [skjolber/sesseltjonna-csv#38]
In a large csv file is really import to catch and eventually manage parsing error for some rows (for example wrong character in some csv rows) but how i can archive this without stop reading remaining rows?
Right now with a try catch clause i create an infinite loop because i can't step forward the error

**Comment by skjolber** [comment]
@paulux84  The reader assumes the file is correctly escaped, it does not handle errors, and there is no universially good way to handle errors (i.e. regain state), perhaps except scanning for the next line (assuming no linebreaks in quoted text).

**Comment by skjolber** [comment]
@paulux84 do you have any concrete examples of errors which could be handled?

See https://github.com/skjolber/sesseltjonna-csv/pull/40 for access to raw stream / skipping.

**Comment by skjolber** [comment]
@paulux84 some improvements released with 1.0.23.
